# -*- coding: utf-8 -*-
"""chat_rust.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eZSg8FE5Am777cbKtDIqXaWEKlWY7Zd2
"""









!curl -fsSL https://ollama.com/install.sh | sh

!nohup ollama serve &



!ollama run llama3.2:1b

!git clone https://github.com/randyungaro/rust-chat-app

# Commented out IPython magic to ensure Python compatibility.
# %cd rust-chat-app

!cargo run

!curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

import os
os.environ['PATH'] += ":/root/.cargo/bin"

!cargo --version

!cargo run



!curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

import os
os.environ['PATH'] += ":/root/.cargo/bin"

!cargo --version

!ollama list

!pip install pyngrok

XXXXX


from pyngrok import ngrok
import threading
import time

ngrok_token = "XXXXX"
ngrok.set_auth_token(ngrok_token)

# Start ngrok in a separate thread to avoid blocking
def start_ngrok():
    public_url = ngrok.connect(3000).public_url
    print(f"🚀 Ngrok Tunnel Open: {public_url}")

ngrok_thread = threading.Thread(target=start_ngrok)
ngrok_thread.start()

# Wait for ngrok to start (optional)
time.sleep(5)

# Execute your node.js script
!node hello-world.js

!which node

!pip install pyngrok

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/rust-chat-app

"""### شغال"""

!nohup ollama serve &

from pyngrok import ngrok
import threading
import time

ngrok_token = "XXXXX"
ngrok.set_auth_token(ngrok_token)

# Start ngrok in a separate thread to avoid blocking
def start_ngrok():
    public_url = ngrok.connect(8000).public_url
    print(f"🚀 Ngrok Tunnel Open: {public_url}")

ngrok_thread = threading.Thread(target=start_ngrok)
ngrok_thread.start()

# Wait for ngrok to start (optional)
time.sleep(5)

# Execute your node.js script
!cargo run

